<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Undertow</AssemblyName>
    <RootNamespace>Jellyembifier</RootNamespace>
    <Version>0.46.1</Version>
    <AssemblyVersion>0.46.1.0</AssemblyVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../assets/plugin/channel.png" LogicalName="Jellyembifier.channel.png" />
    <EmbeddedResource Include="../../assets/plugin/channel-card.png" LogicalName="Jellyembifier.channel-card.png" />
    <EmbeddedResource Include="../../assets/plugin/folders/*.png" LogicalName="Jellyembifier.Assets.%(Filename)%(Extension)" />
    <Reference Include="MediaBrowser.Controller"><HintPath>../../libs/MediaBrowser.Controller.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MediaBrowser.Common"><HintPath>../../libs/MediaBrowser.Common.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="MediaBrowser.Model"><HintPath>../../libs/MediaBrowser.Model.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Emby.Media.Model"><HintPath>../../libs/Emby.Media.Model.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Emby.Web.GenericEdit"><HintPath>../../libs/Emby.Web.GenericEdit.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Emby.Web.GenericUI"><HintPath>../../libs/Emby.Web.GenericUI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.IO.Pipelines"><HintPath>../../libs/System.IO.Pipelines.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
